export const BOARD_INFO_LOAD = 'BOARD_INFO_LOAD';
export const BOARD_INFO_LOAD_START = 'BOARD_INFO_LOAD_START';
export const BOARD_INFO_LOAD_FINISH = 'BOARD_INFO_LOAD_FINISHED';
export const BOARD_INFO_LOAD_FAIL = 'BOARD_INFO_LOAD_FAIL';

export const BOARD_INFO_DELETE = 'BOARD_INFO_DELETE';
export const BOARD_INFO_DELETE_START = 'BOARD_INFO_DELETE_START';
export const BOARD_INFO_DELETE_FINISH = 'BOARD_INFO_DELETE_FINISH';

export const BOARD_INFO_CHANGE_TITLE = 'BOARD_INFO_CHANGE_TITLE';
export const BOARD_INFO_CHANGE_TITLE_START = 'BOARD_INFO_CHANGE_TITLE_START';
export const BOARD_INFO_CHANGE_TITLE_FINISH = 'BOARD_INFO_CHANGE_TITLE_FINISH';
export const BOARD_INFO_CHANGE_TITLE_FAIL = 'BOARD_INFO_CHANGE_TITLE_FAIL';
