export const BOARD_INFO_LOAD_START = 'BOARD_INFO_LOAD_START';
export const BOARD_INFO_LOAD_FINISH = 'BOARD_INFO_LOAD_FINISHED';
export const BOARD_INFO_DELETE_START = 'BOARD_INFO_DELETE_START';
export const BOARD_INFO_DELETE_FINISH = 'BOARD_INFO_DELETE_FINISH';
